# Generated by Django 4.2.6 on 2024-02-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='end',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='init',
        ),
    ]
