# Generated by Django 4.2.6 on 2024-02-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_end_order_date_time_remove_order_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='refund',
        ),
    ]
