# Generated by Django 4.2.6 on 2024-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
