# Generated by Django 4.2.6 on 2024-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('business', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón social')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('is_state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiales',
            },
        ),
    ]
