# Generated by Django 4.2.6 on 2024-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(default='', max_length=15, unique=True)),
                ('names', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
